### ISSUE TITLE
Error: no such option

### ISSUE THREAD

**Issue by Rohit-Medpalli123** [doyou89/RPBot#2]
Hi,
I am getting the below error after executing the rpbot command

`python -m rpbot.run --verbose --RP_UUID:"8778702f-2657-4093-81c7-d05dcf705197" --RP_ENDPOINT:"http://ip172-08-0-27-c2dmb8abcepg00dv5n1g-8080.direct.labs.play-with-docker.com" --RP_LAUNCH:"default_TEST_EXAMPLE" --RP_PROJECT:"default_personal" output.xml`

**On terminal error**
 `run.py: error: no such option: --RP_ENDPOINT:http://ip172-08-0-27-c2dmb8abcepg00dv5n1g-8080.direct.labs.play-with-docker.com`

I am not sure what I am doing wrong, Can you please guide me to solve this problem?

Thanks & Regards

**Comment by doyou89** [comment]
Hi @Rohit-Medpalli123 
Please remove colon(:) from options. You should write like below.
```sh
python -m rpbot.run --verbose --RP_UUID "8778702f-2657-4093-81c7-d05dcf705197" --RP_ENDPOINT "http://ip172-08-0-27-c2dmb8abcepg00dv5n1g-8080.direct.labs.play-with-docker.com" --RP_LAUNCH "default_TEST_EXAMPLE" --RP_PROJECT "default_personal" output.xml
```

**Comment by Rohit-Medpalli123** [comment]
Thanks for replying @doyou89 
After executing the above command,i am getting the below error now 
`Usage: run.py [options]

run.py: error: file "8778702f-2657-4093-81c7-d05dcf705197" does not exist`

**Comment by doyou89** [comment]
--verbose should have LEVEL.
```sh
python -m rpbot.run --verbose INFO --RP_UUID "8778702f-2657-4093-81c7-d05dcf705197" --RP_ENDPOINT "http://ip172-08-0-27-c2dmb8abcepg00dv5n1g-8080.direct.labs.play-with-docker.com" --RP_LAUNCH "default_TEST_EXAMPLE" --RP_PROJECT "default_personal" output.xml

```

**Comment by Rohit-Medpalli123** [comment]
@doyou89  After executing the above-mentioned command, I am observing below error
File "/media/jarvis/AutomationRepos/rfvscode/lib/python3.7/site-packages/rpbot/reportportal/service.py", line 47, in _get_launch_attributes
    system_info = RobotService.rp.get_system_information(
AttributeError: 'ReportPortalService' object has no attribute 'get_system_information'

https://github.com/reportportal/agent-Python-RobotFramework/blob/master/robotframework_reportportal/service.py  --> doesn't have a "'get_system_information'" method

**Comment by doyou89** [comment]
It's due to the change of reportportal-client 5.0.12 version.
I'll update my code for the change.

**Comment by doyou89** [comment]
0.4.2 released. Try this, please.

**Comment by Rohit-Medpalli123** [comment]
@doyou89 working now, thanks for fixing
